ARG NODE_VERSION=20
ARG CLIENT_PORT=3001

# Используем официальный образ Node.js
FROM node:$NODE_VERSION-buster AS builder

# Рабочая директория внутри контейнера
WORKDIR /app

COPY package.json yarn.lock ./
# RUN yarn config set "strict-ssl" false -g
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build --scope=client


FROM nginx:latest AS production

COPY --from=builder /app/packages/client/dist/ /app/client/dist/

EXPOSE $CLIENT_PORT
